### PR TITLE
Individual Project - Final

### PR DESCRIPTION
**Pull request by Consti10**
Work in progress.

### CODE REVIEW

**Comment by changkun** [comment]
Is the submission still in progress? Can we rename the title and drop the "work in progress"?

**Comment by changkun** [comment]
It looks like the final presentation slides is not attached so far, did I missed anything?

**Comment by Consti10** [comment]
I've added the presentation under /talks/3_final and moved the used screenshots into a subdirectory for better structure.

**Review by changkun — APPROVED** [review]
Great project :)

**Pull request merged**
