### PR TITLE
Project Final

### PR DESCRIPTION
**Pull request by alvaxgln**
Implemented first Functions for Edge Flip and Angle Based smoothing

### CODE REVIEW

**Comment by alvaxgln** [comment]
Here is the link for the video submission: https://www.youtube.com/watch?v=-01tQyUI47A

**Comment by changkun** [comment]
There is one thing left for you to do before I merge your code. We need to resolve the code licensing. I don't see newly added files but only modifications from the original code template that I provided. However, the newly added code is authored by you. We need provide this information in every license header:

```diff
// Copyright (c) 2021 LMU Munich Geometry Processing Authors. All rights reserved.
// Created by Changkun Ou <https://changkun.de>.
+// Modified by Jakob Schmid <your-email-address or website>
//
// Use of this source code is governed by a GNU GPLv3 license that can be found
// in the LICENSE file.
```

See https://github.com/mimuc/gp/tree/ws2122/projects#code-submission for more details.

**Comment by alvaxgln** [comment]
> There is one thing left for you to do before I merge your code. We need to resolve the code licensing. I don't see newly added files but only modifications from the original code template that I provided. However, the newly added code is authored by you. We need provide this information in every license header:
> 
> ```diff
> // Copyright (c) 2021 LMU Munich Geometry Processing Authors. All rights reserved.
> // Created by Changkun Ou <https://changkun.de>.
> +// Modified by Jakob Schmid <your-email-address or website>
> //
> // Use of this source code is governed by a GNU GPLv3 license that can be found
> // in the LICENSE file.
> ```
> 
> See https://github.com/mimuc/gp/tree/ws2122/projects#code-submission for more details.

Sure, I added the info to the files I modified, now.

**Review by changkun — APPROVED** [review]
Great project :)

**Pull request merged**
