### PR TITLE
Project Final

### PR DESCRIPTION
**Pull request by nico778**

### CODE REVIEW

**Comment by changkun** [comment]
It looks like the submission missed the video? Could you quickly provide a video link to the readme file? Did I overlooped the submission?

**Comment by changkun** [comment]
There is one thing left for you to do before I merge your code. We need to resolve the code licensing. For newly added files, use the format mentioned in https://github.com/mimuc/gp/tree/ws2122/projects#code-submission.
For modifications from the original code template that I provided, use the following in every license header:

```diff
// Copyright (c) 2021 LMU Munich Geometry Processing Authors. All rights reserved.
// Created by Changkun Ou <https://changkun.de>.
+// Modified by Nicolas Mogicato <your-email-address or website>
//
// Use of this source code is governed by a GNU GPLv3 license that can be found
// in the LICENSE file.
```

Only actual code is required, files such as `*.json` and etc are not necessary.

**Comment by nico778** [comment]
the video is in the gp/projects/nico778 folder.
thanks, the licensing should be correct now. The *.json are the same as in the homework skeleton. Should I remove them nevertheless?

**Review by changkun — APPROVED** [review]
Nice project :)

**Pull request merged**
